schema_version: 1

context:
  name: mininterface
  version: "1.1.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mininterface-${{ version }}.tar.gz
  sha256: 88ce2f178e492ac57c0acb94a68f3c0ba78b76c01e34720bfacfe7e856fa4e03

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - mininterface = mininterface.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=2.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - simple-term-menu
    - annotated-types
    # Include basica requirements (listed as optional upstream)
    - tyro >=0.9,<0.10
    - pyyaml
    - humanize
    - textual <2.0.0
    - tkinter-tooltip
    - tkinter_form ==0.2.1
    - tkscrollableframe

tests:
  - python:
      imports:
        - mininterface
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - mininterface --help

about:
  homepage: https://github.com/CZ-NIC/mininterface
  summary: A minimal access to GUI, TUI, CLI and config
  license: LGPL-3.0-only
  license_file: LICENSE
  documentation: https://cz-nic.github.io/mininterface/Overview/

extra:
  recipe-maintainers:
    - thewchan
